### ISSUE TITLE
master version is now cloud ready (Specific to d7.... filenames)

### ISSUE THREAD

**Issue by qjhart** [ucd-library/wine-price-extraction#13]
@jcarlen / @jrmerz I have updated the master setup to be the one used for cloud-data ready.  This has a couple of implications.:

1) The code we run, doesn't have any explicit `UCD_Lehmann` filename making.  This is how we [get file_id](https://github.com/ucd-library/wine-price-extraction/blob/e1eb0d4b36bd38722fb7363551bea4cae9ff8b9f/dsi/scripts/run_wine_database_one_page.R#L120)  where we just use the filename.

2) I've eliminated the small number of locations where file_number was used.

3) There **is** a cloud specific issue with the parse_items_data.R file (in tablewine) where we have a [filepatter](https://github.com/ucd-library/wine-price-extraction/blob/e1eb0d4b36bd38722fb7363551bea4cae9ff8b9f/dsi/tablewine/R/parse_items_data.R#L137) for the files to include.  There is probably a better way to avoid the _data1 files, so that you can continue to use the UCD_Lehmann names, but I'm not sure what that is.

4) I do not use your ENTRY_TRUTH.csv file, which included UCD_Lehman names, instead, I continue to use the `truth_all.csv` file.

If you want to continue to run on the UCD_Lehmann files, we'll need to branch on these issues.

**Comment by qjhart** [comment]
Oh, and I've left [run_wine_database](https://github.com/ucd-library/wine-price-extraction/blob/master/dsi/scripts/run_wine_database.R) the old way, and we use [run_wine_database_one_page](https://github.com/ucd-library/wine-price-extraction/blob/master/dsi/scripts/run_wine_database_one_page.R)

**Comment by jcarlen** [comment]
That all makes sense to me. My setup is useful to have for testing, but I’m the only one who needs it. Should I create a new branch for my scripts? 

Have you had a chance to think about what fields you would want as evaluation fields in the final table? E.g. ratio for multi-column tables, the flags I had in before, various metrics vs. truth when possible, e.g. lev distance. I’ll re-work my evaluation code to act on final tables once I have a better idea of what to include. 

Best,
Jane

**Comment by qjhart** [comment]
@jcarlen, yes if you need to create a special set of scripts for testing, please create a branch for that.
