### ISSUE TITLE
Verify the accuracy of the Tesseract Package

### ISSUE THREAD

**Issue by qjhart** [ucd-library/wine-price-extraction#17]
@jcarlen and I find that we get different results from the OCR of same images.  This seems to lead to problems later on on the processing potentially.  We need to figure out why this is the case.  I imagine that it could be either the tesseract package, the configuration or the R library.  My inclination is to think it's the configuration, then maybe the package, and finally the R implementation.

This is the current setup on the Docker file.
``` bash
> tesseract -v
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX
 Found SSE
```
There are over 600 configuration parameters.  I'm not sure how we can compare between our setups on that.  

Also, tesseract version 5 does not seem to run with Rtesseract, so we can't use that.  I'll try the latest 4.x version.

**Comment by qjhart** [comment]
@jcarlen can you run `tesseract -v` on your computer for comparison?

**Comment by jcarlen** [comment]
I have version 4:

tesseract 4.0.0
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE

**Comment by qjhart** [comment]
We have found this is the result not of tessearct, but of the eng.trainneddata dataset.  The data that is shipped with the standard tesseract-ocr-eng package is bad.   The version downloaded from the website works better, however it doesn't match the one Jane used.  We are currently standardizing on Janes, though the docker config includes both hers and the tesseract github version.

The names are:
* **jane** The version from Jane's computer
* **github** the Current (though 1yr old) tesseract version

The reason to stick with Jane's is that the Rtesseract seems to fail with the new version, could this be a UTF thing?
