### ISSUE TITLE
Proper Labeling

### ISSUE THREAD

**Issue by qjhart** [ucd-library/wine-price-extraction#9]
In general, what is the preferred name of the wine? The whole line between id and price, e.g. "CHATEAU GREYSAC 1964 (Medoc)" or just the name, i.e. "CHATEAU GREYSAC" (assuming we are able to trim region / producer, year and other info)?
What are the essential information for the researchers that will be working with our output?

Generally, with the exception of the vintage, you should copy the entry faithfully as the name.  This doesn't include vintage, which has it's separate column, or phrases that are obviously not part of the title, eg. `1993 Moet&Chandon, A great Treat! ...... 34.00`

In addition, you should maintain the use of capitalization, and items like commas and parens.  

There are two reasons for this.  First, the rules for the names of wines, and the producers, etc. is very complicated, and not something that non-experts can easily determine.  (This is why in the end we even removed the notion of a producer.)  

The second reason,  is this will help determine things like; what were the big selling points for wine (St. Emillion?) and where they based on the wine nameing standards, and did they stay that way thoughout time.

**Comment by qjhart** [comment]
3971 - same problem. Wines at the top start with "Medoc" and "St. Emilion" (175, 185), then have "Chateau something", while other wines start with "Chateau ..." followed by "Medoc" and "St. Emilion" (173, 268)

![image](https://user-images.githubusercontent.com/344953/48719350-2028bb80-ebd2-11e8-8ea6-e3e7024e0b08.png)


![image](https://user-images.githubusercontent.com/344953/48719596-c07ee000-ebd2-11e8-964b-3e5df2130cee.png)

**Comment by qjhart** [comment]
3408 - several wines at the bottom (286, 638, 261, 660, ...) have names consisting of two (or more) phrases written in capital letters separated by coma, e.g. 286 MOREY, CLOS DE LA ROCHE, CUVEE VIELLES VIGNES. What's the name here? In most cases names are 2-3-4 words (upper-case), then coma or year, then region / producer (lower-case)

![image](https://user-images.githubusercontent.com/344953/48720309-4c453c00-ebd4-11e8-93b2-ed28dd2acf91.png)

**Comment by qjhart** [comment]
*0006 - bottom right - should we include year in the name since all wines have the same name?*
No.  The wine name should be the same,  the vintage changes in those examples.

![image](https://user-images.githubusercontent.com/344953/48718009-64668c80-ebcf-11e8-819c-d55de7b94416.png)

**Comment by qjhart** [comment]
*1459 - wines 350 and 342 starts with "Saint Emilion" and "Graves", which are often used as a regions in other wines (e.g. wine 1108 on the same page). Additionally, the section title says that the Talleyrand is the region for this wines. What should be the name for wines like these two (350, 342)?*

Still just copy the name as written, include the name and region.

![image](https://user-images.githubusercontent.com/344953/48718894-1b173c80-ebd1-11e8-9a5c-53263d366d76.png)

![image](https://user-images.githubusercontent.com/344953/48718822-f58a3300-ebd0-11e8-9da1-299741ba949d.png)

**Comment by jcarlen** [comment]
Thanks for all this information. Based on this, Stan will create the following fields based on the Name, recognizing that only the "Name" will always be filled in and other information may be missing:

**Name** - Includes everything in the name box in original fonts/styles, e.g. "SAINT EMILION 1975, Talleyrand"

**The following fields, which are also in PTV:**
Country
Vintage (Year)
Wine Type (Still, Sparkling, Fortified)
Wine Color (Red, White, Rose)

**Additional fields that may incorporate** [Kaggle wine data](https://www.kaggle.com/zynicide/wine-reviews#winemag-data-130k-v2.csv)
Province/State
Region
Designation (e..g Reserve, Estate)
Variety (e.g. Pinot Noir, Chardonnay)

After Stan's parser does its thing, we will attempt to fill in missing fields above using other information on the page, e.g. the year may be above the price table and the wine color may be in the page header.

**Comment by ssaganowski** [comment]
> **Name** - Includes everything in the name box in original fonts/styles, e.g. "SAINT EMILION 1975, Talleyrand"

I think the final decision is everything except the vintage, so in your example "SAINT EMILION, Talleyrand"

**Comment by jcarlen** [comment]
Ah yes, you're correct. Let's still retain a field in our output called something like Name_raw with the full name (including year) as it may be useful for quantifying OCR success.
